---
title: "data_analysis.R"
author: "Jess Devine"
date: "2025-03-06"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# Load packages
library(tidyverse)
library(patchwork)
library(dplyr)
library(car)
library(FSA) 
library(lubridate)
library(stringr)

```


```{r plots for data exploration}
# Function to create scatterplots
create_scatter <- function(data, x_var, y_var, x_label, y_label) {
  ggplot(data, aes(x = {{ x_var }}, y = {{ y_var }})) +
    geom_point(color = "black", alpha = 0.7, size = 0.5) +  
    theme_minimal() +
    labs(x = x_label, y = y_label)
}

# Function to create boxplots
create_boxplot <- function(data, x_var, y_var, x_label, y_label) {
  ggplot(data, aes(x = as.factor({{ x_var }}), y = {{ y_var }})) +
    geom_boxplot() +
    theme_minimal() +
    labs(x = x_label, y = y_label)
}

# Incubation Period Plots
p1 <- create_scatter(tidy_data, Rainfallspecific, incubation_period, "", "Incubation Period (days)")
p2 <- create_scatter(tidy_data, meanmaxTspecific, incubation_period, "", "")
p3 <- create_boxplot(tidy_data, Groupsize, incubation_period, "", "")

# Chick Mass Plots
p4 <- create_scatter(tidy_data, Rainfallspecific, Chickmass, "Rainfall (mm)", "Chick Mass (g)")
p5 <- create_scatter(tidy_data, meanmaxTspecific, Chickmass, "Mean Max Temperature (°C)", "")
p6 <- create_boxplot(tidy_data, Groupsize, Chickmass, "Group Size", "")

# Arrange in 2x3 panel layout
(p1 + p2 + p3) / (p4 + p5 + p6)

```

Figure 1: The incubation period of eggs (top panel) and mass of chicks (bottom panel) plotted against rainfall in mm (left panel), mean maximum temperature °C (middle panel) and group size (right panel). 

```{r analysis}
# Shapiro-Wilk test for normality
shapiro.test(tidy_data$incubation_period)  
shapiro.test(tidy_data$Chickmass) 

# Kruskal-Wallis Test 
kruskal.test(incubation_period ~ as.factor(Groupsize), data = tidy_data)
kruskal.test(Chickmass ~ as.factor(Groupsize), data = tidy_data)

# Dunn’s test for pairwise comparisons
dunnTest(incubation_period ~ as.factor(Groupsize), data = tidy_data, method = "bonferroni")
dunnTest(Chickmass ~ as.factor(Groupsize), data = tidy_data, method = "bonferroni")
``` 